imports:
    - javascript
    - php

tools:
  php_code_sniffer:
    filter:
      excluded-paths: [ spec/* ]

  php_analyzer:
    filter:
      excluded-paths: [ spec/* ]

filter:
  excluded_paths:
    - docs/*
    - vendor/*
    - src/PhpSpec/CodeGenerator/Generator/*Generator.php # fatal bug in analyzer