language: php

php: [5.3.3, 5.3, 5.4, 5.5, 5.6, hhvm, hhvm-nightly]

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then echo -e '\nhhvm.libxml.ext_entity_whitelist = "file"' | sudo tee -a /etc/hhvm/php.ini; fi
  - composer self-update
  - export COMPOSER_ROOT_VERSION=2.0.0-RC3

install:
  - composer install --prefer-source

script:
  - bin/phpspec run
  - ./vendor/bin/behat --format=pretty
